package library_management_sysytem;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Scanner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author rohit
 */
public class ServerChatWindow extends javax.swing.JFrame {
    
    static ServerSocket serverSocket = null;
    static Socket socket = null;
    static DataInputStream inputStream;
    static DataOutputStream outputStream;
    static Scanner in = new Scanner(System.in);

    /**
     * Creates new form ChatWindow
     */
    public ServerChatWindow() {
//
//        try {
//            serverSocket = new ServerSocket(4000);
//            System.out.println("Awaiting Connection");
//            socket = serverSocket.accept();
//            System.out.println("Connection From " + socket + " Established");
//            setVisible(true);
//            inputStream = new DataInputStream(socket.getInputStream());
//            outputStream = new DataOutputStream(socket.getOutputStream());
//            String inputReceivedString = "";
//            String sendData = "";
//            while (true) {
//                inputReceivedString = inputStream.readUTF();
//                ServerArea.setText(ServerArea.getText() + "\n" + "CLIENT : " + inputReceivedString);
//
//            }
//        } catch (Exception e) {
//        }

        initComponents();
//        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ServerArea = new javax.swing.JTextArea();
        ServerText = new javax.swing.JTextField();
        ServerSend = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(60, 60, 60));

        ServerArea.setColumns(20);
        ServerArea.setRows(5);
        jScrollPane1.setViewportView(ServerArea);

        ServerText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServerTextActionPerformed(evt);
            }
        });

        ServerSend.setBackground(new java.awt.Color(125, 112, 152));
        ServerSend.setForeground(new java.awt.Color(255, 255, 255));
        ServerSend.setText("Send");
        ServerSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServerSendActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(125, 112, 152));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("End");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Server");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ServerText, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ServerSend, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ServerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ServerSend))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ServerTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServerTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServerTextActionPerformed

    private void ServerSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServerSendActionPerformed
        
        try {
            String sendData = ServerText.getText().trim();
            outputStream.writeUTF(sendData);
            ServerArea.setText(ServerArea.getText() + "\n" + "\t\t\t" + "YOU : " + sendData);
            ServerText.setText("");
        } catch (Exception e) {
            System.out.println(e);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_ServerSendActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            outputStream.close();
            inputStream.close();
            socket.close();
            serverSocket.close();
        } catch (Exception e) {
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    @Override
    public void setVisible(boolean b) {
        
        super.setVisible(b); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void main(String args[]) {
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ServerChatWindow().setVisible(true);
//            }
//        });
        setVisible(true);
        try {
            serverSocket = new ServerSocket(4000);
            System.out.println("Awaiting Connection");
            socket = serverSocket.accept();
            System.out.println("Connection From " + socket + " Established");
            inputStream = new DataInputStream(socket.getInputStream());
            outputStream = new DataOutputStream(socket.getOutputStream());
            String inputReceivedString = "";
            String sendData = "";
            while (true) {
                inputReceivedString = inputStream.readUTF();
                ServerArea.setText(ServerArea.getText() + "\n" + "CLIENT : " + inputReceivedString);
                
            }
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextArea ServerArea;
    private javax.swing.JButton ServerSend;
    private javax.swing.JTextField ServerText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
